service: ruby-serverless-example
# app and org for use with dashboard.serverless.com
app: my-face

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: ruby2.5
  region: us-west-2

functions:
  returnMyImage:
    handler: functions/return-my-image/handler.return_my_image
    events:
      - http:
          path: /images
          method: get
  returnChris:
    handler: functions/return-my-site/handler.return_my_site
    events:
      - http:
          path: /chris
          method: get